### ISSUE TITLE
GhIDA analysis failed

### ISSUE THREAD

**Issue by SteinsGatep001** [Cisco-Talos/GhIDA#10] opened 2019-11-22 04:59 UTC
Environment: Windows10, IDA Pro 7.3, ghidra 9.0.4, python2.7.16
## error log
```bash
GhIDA:: [DEBUG] found 0 symbols
GhIDA:: [INFO] XML exporting completed
GhIDA:: [DEBUG] decompiled cache miss (3560)
GhIDA:: [DEBUG] Decompiling 3560
GhIDA:: [DEBUG] EXPORT_XML_FILE: False
GhIDA:: [INFO] Ghidra headless (timeout: 300s)
GhIDA:: [INFO] Waiting Ghidra headless analysis to finish...
GhIDA:: [INFO] Ghidra analysis completed!
GhIDA:: [!] No JSON object could be decoded
GhIDA:: [!] Ghidra headless analysis failed
GhIDA:: [!] Decompilation interrupted.
```

**Comment by xSailon** [comment] 2020-01-11 14:54
here's mine, using IDA Pro 7.2, ghidra 9.1.1, python 2.7.17

```
GhIDA:: [DEBUG] found 0 symbols
GhIDA:: [INFO] XML exporting completed
GhIDA:: [DEBUG] decompiled cache miss (20568ff0)
GhIDA:: [DEBUG] Decompiling 20568ff0
GhIDA:: [DEBUG] EXPORT_XML_FILE: False
GhIDA:: [INFO] Ghidra headless (timeout: 300s)
GhIDA:: [INFO] Waiting Ghidra headless analysis to finish...
GhIDA:: [INFO] Ghidra analysis completed!
GhIDA:: [!] No JSON object could be decoded
GhIDA:: [!] Ghidra headless analysis failed
GhIDA:: [!] Decompilation interrupted.
```

**Comment by jimmy-sonny** [comment] 2020-01-31 18:43
Can you please give more information about the binary analysed? Does Ghidra correctly open and analyse that binary? The issue seems to be related to Ghidra analysis.

**Comment by jimmy-sonny** [comment] 2020-01-31 18:52
This may happen when the Ghidra analysis exceeds the timeout. Duplicate of #3.

**Comment by jimmy-sonny** [comment] 2020-02-07 17:42
#3 has been fixed. Closing the issue.

**Closed by jimmy-sonny** 2020-02-07 17:42 UTC
Labels: duplicate
